### ISSUE TITLE
Tracking issue for different perf tools

### ISSUE THREAD

**Issue by lilianmoraru** [lilianmoraru/cxxbasics-perftools#1]
- [ ] [gprof](https://github.com/lilianmoraru/cxxbasics-perftools/issues/2)
- [ ] [valgrind(Callgrind, Massif)](https://github.com/lilianmoraru/cxxbasics-perftools/issues/3)
- [ ] [kcachegrind](https://github.com/lilianmoraru/cxxbasics-perftools/issues/4)
- [ ] [Linux perf](https://github.com/lilianmoraru/cxxbasics-perftools/issues/5)
- [ ] [hotspot(requires Linux perf support)](https://github.com/lilianmoraru/cxxbasics-perftools/issues/6)
- [ ] [gperftools](https://github.com/lilianmoraru/cxxbasics-perftools/issues/7)
- [ ] [easy_profiler](https://github.com/lilianmoraru/cxxbasics-perftools/issues/8)
- [ ] [bloaty](https://github.com/lilianmoraru/cxxbasics-perftools/issues/9)
- [ ] [coz](https://github.com/lilianmoraru/cxxbasics-perftools/issues/10)
- [ ] [heaptrack](https://github.com/lilianmoraru/cxxbasics-perftools/issues/11)

**Comment by lilianmoraru** [comment]
Might be helpful: http://gernotklingler.com/blog/gprof-valgrind-gperftools-evaluation-tools-application-level-cpu-profiling-linux/
